version: '3.8'

services:
  app:
    image: node:16
    container_name: fastify-app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=root  
      - MYSQL_DB=root
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: root  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
